### ISSUE TITLE
Internal server error when logging in with invalid cookie

### ISSUE THREAD

**Issue by joe4dev** [sealuzh/cloud-workbench#28]
## Request

```
GET <SERVER>/users/sign_in
```

## Client error
```
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
```

## Workaround

Delete the `_cloud_benchmarking_session` cookie

## Server error log

```
I, [2019-01-03T16:54:47.590453 #3950]  INFO -- : Started GET "/users/sign_in" for <IP_ADDRESS_REDACTED> at 2019-01-03 16:54:47 +0100
I, [2019-01-03T16:54:47.591442 #3950]  INFO -- : Processing by Devise::SessionsController#new as HTML
I, [2019-01-03T16:54:47.593645 #3950]  INFO -- :   Rendering devise/sessions/new.html.erb within layouts/devise
I, [2019-01-03T16:54:47.596279 #3950]  INFO -- :   Rendered devise/sessions/new.html.erb within layouts/devise (2.5ms)
I, [2019-01-03T16:54:47.597647 #3950]  INFO -- :   Rendered layouts/_head.html.erb (1.0ms)
I, [2019-01-03T16:54:47.597940 #3950]  INFO -- :   Rendered layouts/_progress_bar.html.erb (0.0ms)
I, [2019-01-03T16:54:47.601888 #3950]  INFO -- :   Rendered layouts/_bootstrap_flash.html.erb (3.3ms)
I, [2019-01-03T16:54:47.602503 #3950]  INFO -- : Completed 500 Internal Server Error in 11ms (ActiveRecord: 0.0ms)
F, [2019-01-03T16:54:47.603852 #3950] FATAL -- :
F, [2019-01-03T16:54:47.603933 #3950] FATAL -- : ActionView::Template::Error (undefined method `empty?' for true:TrueClass):
F, [2019-01-03T16:54:47.604248 #3950] FATAL -- :     1: <% flash.each do |key, value| %>
    2:   <div class="alert alert-<%= flash_class(key) %> alert-dismissable">
    3:     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    4:     <%= sanitize(value) %>
    5:     <%= flash_icon(key) %>
    6:   </div>
    7: <% end %>
F, [2019-01-03T16:54:47.604322 #3950] FATAL -- :
F, [2019-01-03T16:54:47.604456 #3950] FATAL -- : app/views/layouts/_bootstrap_flash.html.erb:4:in `block in _app_views_layouts__bootstrap_flash_html_erb___608194816731503225_47187520741960'
app/views/layouts/_bootstrap_flash.html.erb:1:in `_app_views_layouts__bootstrap_flash_html_erb___608194816731503225_47187520741960'
app/views/layouts/devise.html.erb:10:in `_app_views_layouts_devise_html_erb___4096807222462644144_47187521122260'
I, [2019-01-03T16:54:47.606586 #3950]  INFO -- : Processing by ErrorsController#show as HTML
I, [2019-01-03T16:54:47.606680 #3950]  INFO -- :   Parameters: {"code"=>"500"}
I, [2019-01-03T16:54:47.607749 #3950]  INFO -- :   Rendering errors/500.html.erb within layouts/application
I, [2019-01-03T16:54:47.608513 #3950]  INFO -- :   Rendered errors/500.html.erb within layouts/application (0.6ms)
I, [2019-01-03T16:54:47.609575 #3950]  INFO -- :   Rendered layouts/_head.html.erb (0.8ms)
I, [2019-01-03T16:54:47.609875 #3950]  INFO -- :   Rendered layouts/_progress_bar.html.erb (0.0ms)
I, [2019-01-03T16:54:47.610502 #3950]  INFO -- :   Rendered layouts/_top_header.html.erb (0.5ms)
I, [2019-01-03T16:54:47.611694 #3950]  INFO -- :   Rendered layouts/_sidebar.html.erb (0.9ms)
I, [2019-01-03T16:54:47.614867 #3950]  INFO -- :   Rendered layouts/_bootstrap_flash.html.erb (3.0ms)
I, [2019-01-03T16:54:47.615274 #3950]  INFO -- :   Rendered layouts/_main_content.html.erb (4.3ms)
I, [2019-01-03T16:54:47.615571 #3950]  INFO -- : Completed 500 Internal Server Error in 9ms (ActiveRecord: 0.0ms)
Error during failsafe response: undefined method `empty?' for true:TrueClass
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/rails-html-sanitizer-1.0.4/lib/rails/html/sanitizer.rb:118:in `sanitize'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/helpers/sanitize_helper.rb:83:in `sanitize'
  /var/www/cloud-workbench/releases/20190103093234/app/views/layouts/_bootstrap_flash.html.erb:4:in `block in _app_views_layouts__bootstrap_flash_html_erb___608194816731503225_47187520741960'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/flash.rb:200:in `each'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/flash.rb:200:in `each'
  /var/www/cloud-workbench/releases/20190103093234/app/views/layouts/_bootstrap_flash.html.erb:1:in `_app_views_layouts__bootstrap_flash_html_erb___608194816731503225_47187520741960'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/template.rb:159:in `block in render'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:170:in `instrument'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/template.rb:354:in `instrument_render_template'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/template.rb:157:in `render'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/partial_renderer.rb:344:in `block in render_partial'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `block in instrument'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `instrument'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/partial_renderer.rb:333:in `render_partial'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/partial_renderer.rb:312:in `render'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/renderer.rb:49:in `render_partial'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/helpers/rendering_helper.rb:36:in `render'
  /var/www/cloud-workbench/releases/20190103093234/app/views/layouts/_main_content.html.erb:16:in `_app_views_layouts__main_content_html_erb__288316701489487454_47187512999220'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/template.rb:159:in `block in render'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:170:in `instrument'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/template.rb:354:in `instrument_render_template'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/template.rb:157:in `render'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/partial_renderer.rb:344:in `block in render_partial'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `block in instrument'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `instrument'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/partial_renderer.rb:333:in `render_partial'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/partial_renderer.rb:312:in `render'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/renderer.rb:49:in `render_partial'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/helpers/rendering_helper.rb:36:in `render'
  /var/www/cloud-workbench/releases/20190103093234/app/views/layouts/application.html.erb:11:in `_app_views_layouts_application_html_erb___3670812100227249704_47187520607040'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/template.rb:159:in `block in render'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:170:in `instrument'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/template.rb:354:in `instrument_render_template'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/template.rb:157:in `render'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/template_renderer.rb:16:in `render'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/renderer.rb:44:in `render_template'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/renderer/renderer.rb:25:in `render'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/rendering.rb:103:in `_render_template'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/streaming.rb:219:in `_render_template'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/rendering.rb:84:in `render_to_body'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/rendering.rb:25:in `render'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/rendering.rb:36:in `render'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
  /usr/local/ruby-2.5.1/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/core_ext/benchmark.rb:14:in `ms'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/railties/controller_runtime.rb:31:in `cleanup_view_runtime'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:45:in `render'
  /var/www/cloud-workbench/releases/20190103093234/app/controllers/errors_controller.rb:5:in `show'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/base.rb:194:in `process_action'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `block in instrument'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `instrument'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/base.rb:134:in `process'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1/lib/action_view/rendering.rb:32:in `process'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal.rb:191:in `dispatch'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal.rb:252:in `dispatch'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:34:in `serve'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:52:in `block in serve'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:35:in `each'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:35:in `serve'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:840:in `call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/show_exceptions.rb:51:in `render_exception'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/show_exceptions.rb:36:in `rescue in call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:38:in `call_app'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:26:in `block in call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:71:in `tagged'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:26:in `call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/silencer-1.0.1/lib/silencer/rails/logger.rb:41:in `call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/runtime.rb:22:in `call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:524:in `call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/tempfile_reaper.rb:15:in `call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/lint.rb:49:in `_call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/lint.rb:37:in `call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/show_exceptions.rb:23:in `call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/common_logger.rb:33:in `call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/chunked.rb:54:in `call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/content_length.rb:15:in `call'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:606:in `process_client'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:701:in `worker_loop'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
  /var/www/cloud-workbench/shared/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:142:in `start'
  /var/www/cloud-workbench/releases/20190103093234/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn:126:in `<top (required)>'
  /var/www/cloud-workbench/releases/20190103093234/bin/unicorn:17:in `load'
  /var/www/cloud-workbench/releases/20190103093234/bin/unicorn:17:in `<main>'
<IP_ADDRESS_REDACTED> - - [03/Jan/2019:16:54:47 +0100] "GET /500 HTTP/1.0" 500 - 0.0268
```

**Comment by joe4dev** [comment]
Verified on deployed server 👍 now shows this error page instead:
![screen shot 2019-01-06 at 19 11 26](https://user-images.githubusercontent.com/8161292/50739924-ed20a280-11e6-11e9-94fe-bf9767f81ca2.png)
